[2025-04-03T12:38:40.172+0000] {processor.py:154} INFO - Started process (PID=1228) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:38:40.173+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:38:40.173+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:38:40.173+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:38:40.177+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:38:40.176+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:38:40.178+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:38:40.193+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.025 seconds
[2025-04-03T12:38:41.207+0000] {processor.py:154} INFO - Started process (PID=1229) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:38:41.208+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:38:41.209+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:38:41.209+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:38:41.215+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:38:41.213+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:38:41.215+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:38:41.238+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.037 seconds
[2025-04-03T12:38:42.220+0000] {processor.py:154} INFO - Started process (PID=1239) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:38:42.221+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:38:42.221+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:38:42.221+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:38:42.223+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:38:42.223+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:38:42.224+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:38:42.236+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.018 seconds
[2025-04-03T12:38:43.243+0000] {processor.py:154} INFO - Started process (PID=1240) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:38:43.244+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:38:43.245+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:38:43.245+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:38:43.249+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:38:43.248+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:38:43.249+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:38:43.266+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.027 seconds
[2025-04-03T12:38:47.519+0000] {processor.py:154} INFO - Started process (PID=1244) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:38:47.521+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:38:47.522+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:38:47.522+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:38:47.526+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:38:47.524+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:38:47.527+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:38:47.547+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.036 seconds
[2025-04-03T12:38:49.620+0000] {processor.py:154} INFO - Started process (PID=1247) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:38:49.622+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:38:49.622+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:38:49.622+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:38:49.626+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:38:49.625+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:38:49.626+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:38:49.642+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.027 seconds
[2025-04-03T12:38:53.671+0000] {processor.py:154} INFO - Started process (PID=1256) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:38:53.673+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:38:53.673+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:38:53.673+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:38:53.677+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:38:53.676+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:38:53.677+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:38:53.694+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.027 seconds
[2025-04-03T12:38:57.775+0000] {processor.py:154} INFO - Started process (PID=1257) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:38:57.776+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:38:57.777+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:38:57.777+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:38:57.781+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:38:57.779+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:38:57.781+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:38:57.800+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.036 seconds
[2025-04-03T12:39:00.825+0000] {processor.py:154} INFO - Started process (PID=1258) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:00.838+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:39:00.844+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:39:00.842+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:00.852+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:39:00.851+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:39:00.853+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:00.867+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.061 seconds
[2025-04-03T12:39:02.910+0000] {processor.py:154} INFO - Started process (PID=1259) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:02.913+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:39:02.916+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:39:02.915+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:02.926+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:39:02.923+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:39:02.929+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:02.959+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.054 seconds
[2025-04-03T12:39:07.989+0000] {processor.py:154} INFO - Started process (PID=1269) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:07.990+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:39:07.992+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:39:07.991+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:07.998+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:39:07.997+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:39:07.999+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:08.028+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.044 seconds
[2025-04-03T12:39:10.055+0000] {processor.py:154} INFO - Started process (PID=1270) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:10.056+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:39:10.058+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:39:10.057+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:10.062+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:39:10.061+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:39:10.063+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:10.086+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.039 seconds
[2025-04-03T12:39:13.133+0000] {processor.py:154} INFO - Started process (PID=1272) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:13.134+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:39:13.135+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:39:13.135+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:13.138+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:39:13.137+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:39:13.139+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:13.157+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.028 seconds
[2025-04-03T12:39:17.354+0000] {processor.py:154} INFO - Started process (PID=1285) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:17.357+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:39:17.358+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:39:17.358+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:17.364+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:39:17.362+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:39:17.365+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:17.388+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.043 seconds
[2025-04-03T12:39:19.422+0000] {processor.py:154} INFO - Started process (PID=1286) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:19.423+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:39:19.424+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:39:19.424+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:19.430+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:39:19.428+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:39:19.430+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:19.456+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.039 seconds
[2025-04-03T12:39:20.502+0000] {processor.py:154} INFO - Started process (PID=1289) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:20.504+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:39:20.505+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:39:20.505+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:20.511+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:39:20.509+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:39:20.511+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:20.536+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.039 seconds
[2025-04-03T12:39:32.670+0000] {processor.py:154} INFO - Started process (PID=1299) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:32.672+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:39:32.673+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:39:32.673+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:32.678+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:39:32.676+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:39:32.679+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:32.703+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.041 seconds
[2025-04-03T12:39:37.756+0000] {processor.py:154} INFO - Started process (PID=1309) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:37.757+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:39:37.758+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:39:37.758+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:37.764+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:39:37.762+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:39:37.765+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:37.785+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.035 seconds
[2025-04-03T12:39:40.827+0000] {processor.py:154} INFO - Started process (PID=1310) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:40.830+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:39:40.831+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:39:40.831+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:40.835+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:39:40.834+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:39:40.835+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:40.855+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.034 seconds
[2025-04-03T12:39:43.918+0000] {processor.py:154} INFO - Started process (PID=1312) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:43.921+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:39:43.922+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:39:43.922+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:43.931+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:39:43.925+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:39:43.932+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:43.947+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.034 seconds
[2025-04-03T12:39:45.989+0000] {processor.py:154} INFO - Started process (PID=1313) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:45.990+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:39:45.991+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:39:45.991+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:45.995+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:39:45.994+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:39:45.996+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:46.014+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.031 seconds
[2025-04-03T12:39:49.115+0000] {processor.py:154} INFO - Started process (PID=1326) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:49.118+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:39:49.119+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:39:49.119+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:49.122+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:39:49.121+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:39:49.123+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:49.137+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.027 seconds
[2025-04-03T12:39:52.221+0000] {processor.py:154} INFO - Started process (PID=1329) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:52.223+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:39:52.224+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:39:52.224+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:52.233+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:39:52.231+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:39:52.233+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:52.256+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.042 seconds
[2025-04-03T12:39:57.255+0000] {processor.py:154} INFO - Started process (PID=1339) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:57.257+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:39:57.257+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:39:57.257+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:57.261+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:39:57.260+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:39:57.261+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:39:57.277+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.024 seconds
[2025-04-03T12:40:02.320+0000] {processor.py:154} INFO - Started process (PID=1340) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:02.322+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:40:02.322+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:40:02.322+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:02.326+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:40:02.325+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:40:02.327+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:02.345+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.028 seconds
[2025-04-03T12:40:04.348+0000] {processor.py:154} INFO - Started process (PID=1341) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:04.350+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:40:04.350+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:40:04.350+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:04.353+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:40:04.352+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:40:04.354+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:04.367+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.022 seconds
[2025-04-03T12:40:05.405+0000] {processor.py:154} INFO - Started process (PID=1342) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:05.406+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:40:05.408+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:40:05.408+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:05.416+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:40:05.414+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:40:05.418+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:05.455+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.054 seconds
[2025-04-03T12:40:09.442+0000] {processor.py:154} INFO - Started process (PID=1352) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:09.443+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:40:09.444+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:40:09.444+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:09.447+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:40:09.446+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:40:09.447+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:09.464+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.025 seconds
[2025-04-03T12:40:11.461+0000] {processor.py:154} INFO - Started process (PID=1353) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:11.462+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:40:11.463+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:40:11.463+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:11.465+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:40:11.464+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:40:11.466+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:11.478+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.019 seconds
[2025-04-03T12:40:14.510+0000] {processor.py:154} INFO - Started process (PID=1355) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:14.511+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:40:14.511+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:40:14.511+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:14.513+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:40:14.512+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:40:14.513+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:14.522+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.014 seconds
[2025-04-03T12:40:17.543+0000] {processor.py:154} INFO - Started process (PID=1356) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:17.545+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:40:17.546+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:40:17.546+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:17.549+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:40:17.548+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:40:17.550+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:17.567+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.028 seconds
[2025-04-03T12:40:28.776+0000] {processor.py:154} INFO - Started process (PID=1371) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:28.777+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:40:28.778+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:40:28.778+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:28.781+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:40:28.780+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:40:28.781+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:28.801+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.029 seconds
[2025-04-03T12:40:33.836+0000] {processor.py:154} INFO - Started process (PID=1381) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:33.837+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:40:33.837+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:40:33.837+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:33.840+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:40:33.839+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:40:33.840+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:33.854+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.021 seconds
[2025-04-03T12:40:37.936+0000] {processor.py:154} INFO - Started process (PID=1382) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:37.940+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:40:37.941+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:40:37.941+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:37.959+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:40:37.958+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:40:37.960+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:37.980+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.057 seconds
[2025-04-03T12:40:39.952+0000] {processor.py:154} INFO - Started process (PID=1391) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:39.953+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:40:39.954+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:40:39.954+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:39.957+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:40:39.956+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:40:39.957+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:39.983+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.034 seconds
[2025-04-03T12:40:44.038+0000] {processor.py:154} INFO - Started process (PID=1393) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:44.040+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:40:44.040+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:40:44.040+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:44.043+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:40:44.042+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:40:44.043+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:44.058+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.024 seconds
[2025-04-03T12:40:49.179+0000] {processor.py:154} INFO - Started process (PID=1397) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:49.180+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:40:49.181+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:40:49.181+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:49.183+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:40:49.182+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:40:49.184+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:49.201+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.024 seconds
[2025-04-03T12:40:56.279+0000] {processor.py:154} INFO - Started process (PID=1409) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:56.280+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:40:56.281+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:40:56.281+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:56.284+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:40:56.283+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:40:56.284+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:40:56.300+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.024 seconds
[2025-04-03T12:41:02.343+0000] {processor.py:154} INFO - Started process (PID=1418) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:02.345+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:41:02.346+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:41:02.346+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:02.352+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:41:02.350+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:41:02.353+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:02.375+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.037 seconds
[2025-04-03T12:41:06.430+0000] {processor.py:154} INFO - Started process (PID=1419) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:06.432+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:41:06.433+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:41:06.433+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:06.438+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:41:06.437+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:41:06.439+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:06.478+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.053 seconds
[2025-04-03T12:41:13.573+0000] {processor.py:154} INFO - Started process (PID=1430) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:13.575+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:41:13.576+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:41:13.576+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:13.581+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:41:13.579+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:41:13.582+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:13.605+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.037 seconds
[2025-04-03T12:41:16.606+0000] {processor.py:154} INFO - Started process (PID=1431) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:16.608+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:41:16.609+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:41:16.609+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:16.613+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:41:16.612+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:41:16.614+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:16.635+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.033 seconds
[2025-04-03T12:41:24.910+0000] {processor.py:154} INFO - Started process (PID=1446) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:24.913+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:41:24.914+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:41:24.914+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:24.919+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:41:24.918+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:41:24.920+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:24.951+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.051 seconds
[2025-04-03T12:41:27.972+0000] {processor.py:154} INFO - Started process (PID=1447) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:27.974+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:41:27.975+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:41:27.975+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:27.979+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:41:27.978+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:41:27.980+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:27.998+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.032 seconds
[2025-04-03T12:41:31.031+0000] {processor.py:154} INFO - Started process (PID=1448) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:31.033+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:41:31.034+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:41:31.034+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:31.039+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:41:31.037+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:41:31.039+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:31.063+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.037 seconds
[2025-04-03T12:41:35.119+0000] {processor.py:154} INFO - Started process (PID=1458) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:35.120+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:41:35.121+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:41:35.121+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:35.127+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:41:35.125+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:41:35.129+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:35.152+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.040 seconds
[2025-04-03T12:41:39.183+0000] {processor.py:154} INFO - Started process (PID=1459) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:39.184+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:41:39.185+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:41:39.185+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:39.187+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:41:39.187+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:41:39.188+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:39.210+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.030 seconds
[2025-04-03T12:41:40.207+0000] {processor.py:154} INFO - Started process (PID=1460) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:40.208+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:41:40.209+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:41:40.209+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:40.212+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:41:40.211+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:41:40.212+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:40.226+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.023 seconds
[2025-04-03T12:41:43.265+0000] {processor.py:154} INFO - Started process (PID=1461) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:43.266+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:41:43.267+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:41:43.267+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:43.270+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:41:43.269+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:41:43.273+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:43.296+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.033 seconds
[2025-04-03T12:41:49.394+0000] {processor.py:154} INFO - Started process (PID=1472) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:49.395+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:41:49.396+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:41:49.396+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:49.401+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:41:49.399+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:41:49.401+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:49.444+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.056 seconds
[2025-04-03T12:41:50.576+0000] {processor.py:154} INFO - Started process (PID=1476) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:50.577+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:41:50.578+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:41:50.578+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:50.582+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:41:50.581+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:41:50.583+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:41:50.599+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.030 seconds
[2025-04-03T12:42:05.795+0000] {processor.py:154} INFO - Started process (PID=1496) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:42:05.797+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:42:05.801+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:42:05.801+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:42:05.815+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:42:05.813+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:42:05.820+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:42:05.872+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.084 seconds
[2025-04-03T12:42:06.823+0000] {processor.py:154} INFO - Started process (PID=1497) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:42:06.825+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:42:06.825+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:42:06.825+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:42:06.830+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:42:06.828+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:42:06.830+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:42:06.848+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.031 seconds
[2025-04-03T12:42:11.922+0000] {processor.py:154} INFO - Started process (PID=1498) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:42:11.924+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:42:11.925+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:42:11.925+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:42:11.931+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:42:11.929+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:42:11.931+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:42:11.955+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.041 seconds
[2025-04-03T12:42:15.001+0000] {processor.py:154} INFO - Started process (PID=1500) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:42:15.002+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:42:15.003+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:42:15.003+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:42:15.006+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:42:15.005+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:42:15.007+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:42:15.023+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.026 seconds
[2025-04-03T12:42:18.087+0000] {processor.py:154} INFO - Started process (PID=1510) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:42:18.089+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:42:18.089+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:42:18.089+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:42:18.095+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:42:18.093+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:42:18.095+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:42:18.127+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.045 seconds
[2025-04-03T12:42:23.339+0000] {processor.py:154} INFO - Started process (PID=1514) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:42:23.342+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:42:23.344+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:42:23.344+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:42:23.350+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:42:23.348+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:42:23.351+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:42:23.371+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.042 seconds
[2025-04-03T12:42:27.426+0000] {processor.py:154} INFO - Started process (PID=1526) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:42:27.428+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:42:27.429+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:42:27.429+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:42:27.434+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:42:27.432+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:42:27.435+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:42:27.481+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.060 seconds
[2025-04-03T12:42:40.554+0000] {processor.py:154} INFO - Started process (PID=1536) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:42:40.555+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:42:40.556+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:42:40.556+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:42:40.559+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:42:40.558+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:42:40.560+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:42:40.578+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.028 seconds
[2025-04-03T12:42:41.583+0000] {processor.py:154} INFO - Started process (PID=1537) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:42:41.584+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:42:41.584+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:42:41.584+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:42:41.586+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:42:41.585+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:42:41.586+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:42:41.595+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.014 seconds
[2025-04-03T12:42:51.858+0000] {processor.py:154} INFO - Started process (PID=1551) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:42:51.859+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:42:51.860+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:42:51.860+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:42:51.863+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:42:51.862+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:42:51.864+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:42:51.878+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.022 seconds
[2025-04-03T12:43:01.990+0000] {processor.py:154} INFO - Started process (PID=1563) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:01.991+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:43:01.991+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:43:01.991+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:01.994+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:43:01.993+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:43:01.995+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:02.023+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.036 seconds
[2025-04-03T12:43:04.014+0000] {processor.py:154} INFO - Started process (PID=1564) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:04.015+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:43:04.015+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:43:04.015+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:04.020+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:43:04.018+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:43:04.020+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:04.039+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.029 seconds
[2025-04-03T12:43:10.172+0000] {processor.py:154} INFO - Started process (PID=1565) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:10.174+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:43:10.175+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:43:10.175+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:10.181+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:43:10.179+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:43:10.181+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:10.206+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.041 seconds
[2025-04-03T12:43:14.256+0000] {processor.py:154} INFO - Started process (PID=1575) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:14.259+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:43:14.260+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:43:14.260+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:14.265+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:43:14.264+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:43:14.266+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:14.287+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.041 seconds
[2025-04-03T12:43:18.350+0000] {processor.py:154} INFO - Started process (PID=1577) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:18.353+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:43:18.354+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:43:18.354+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:18.359+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:43:18.357+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:43:18.360+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:18.380+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.036 seconds
[2025-04-03T12:43:25.615+0000] {processor.py:154} INFO - Started process (PID=1592) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:25.617+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:43:25.618+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:43:25.617+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:25.622+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:43:25.621+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:43:25.623+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:25.651+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.040 seconds
[2025-04-03T12:43:27.634+0000] {processor.py:154} INFO - Started process (PID=1593) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:27.635+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:43:27.636+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:43:27.636+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:27.640+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:43:27.639+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:43:27.641+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:27.658+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.028 seconds
[2025-04-03T12:43:29.669+0000] {processor.py:154} INFO - Started process (PID=1594) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:29.670+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:43:29.671+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:43:29.671+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:29.676+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:43:29.675+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:43:29.676+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:29.698+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.034 seconds
[2025-04-03T12:43:33.765+0000] {processor.py:154} INFO - Started process (PID=1604) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:33.767+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:43:33.769+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:43:33.768+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:33.774+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:43:33.772+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:43:33.774+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:33.795+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.035 seconds
[2025-04-03T12:43:35.793+0000] {processor.py:154} INFO - Started process (PID=1605) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:35.795+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:43:35.795+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:43:35.795+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:35.798+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:43:35.798+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:43:35.799+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:35.811+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.022 seconds
[2025-04-03T12:43:37.837+0000] {processor.py:154} INFO - Started process (PID=1606) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:37.839+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:43:37.841+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:43:37.841+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:37.850+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:43:37.846+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:43:37.851+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:37.885+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.052 seconds
[2025-04-03T12:43:41.929+0000] {processor.py:154} INFO - Started process (PID=1607) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:41.931+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:43:41.932+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:43:41.931+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:41.936+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:43:41.935+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:43:41.936+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:41.960+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.036 seconds
[2025-04-03T12:43:56.314+0000] {processor.py:154} INFO - Started process (PID=1632) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:56.317+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:43:56.317+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:43:56.317+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:56.321+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:43:56.320+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:43:56.322+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:43:56.344+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.037 seconds
[2025-04-03T12:44:25.787+0000] {processor.py:154} INFO - Started process (PID=1655) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:44:25.789+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:44:25.790+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:44:25.790+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:44:25.795+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:44:25.793+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG;
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:44:25.796+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:44:25.815+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.035 seconds
[2025-04-03T12:44:27.851+0000] {processor.py:154} INFO - Started process (PID=1667) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:44:27.853+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:44:27.854+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:44:27.854+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:44:27.860+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:44:27.858+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 1
    import airflow import DAG
                        ^
SyntaxError: invalid syntax
[2025-04-03T12:44:27.861+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:44:27.884+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.037 seconds
[2025-04-03T12:44:35.945+0000] {processor.py:154} INFO - Started process (PID=1668) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:44:35.947+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:44:35.948+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:44:35.948+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:44:35.960+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:44:35.990+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.052 seconds
[2025-04-03T12:45:06.478+0000] {processor.py:154} INFO - Started process (PID=1702) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:45:06.481+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:45:06.482+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:45:06.482+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:45:06.492+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:45:06.509+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.037 seconds
[2025-04-03T12:45:36.538+0000] {processor.py:154} INFO - Started process (PID=1744) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:45:36.541+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:45:36.542+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:45:36.542+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:45:36.553+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:45:36.566+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.034 seconds
[2025-04-03T12:46:06.598+0000] {processor.py:154} INFO - Started process (PID=1783) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:46:06.599+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:46:06.600+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:46:06.600+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:46:06.608+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:46:06.624+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.033 seconds
[2025-04-03T12:46:37.517+0000] {processor.py:154} INFO - Started process (PID=1820) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:46:37.519+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:46:37.520+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:46:37.520+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:46:37.527+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:46:37.537+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.023 seconds
[2025-04-03T12:47:08.104+0000] {processor.py:154} INFO - Started process (PID=1855) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:47:08.106+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:47:08.106+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:47:08.106+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:47:08.111+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:47:08.120+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.019 seconds
[2025-04-03T12:47:38.195+0000] {processor.py:154} INFO - Started process (PID=1886) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:47:38.198+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:47:38.198+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:47:38.198+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:47:38.205+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:47:38.217+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.028 seconds
[2025-04-03T12:48:08.812+0000] {processor.py:154} INFO - Started process (PID=1921) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:48:08.815+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:48:08.816+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:48:08.816+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:48:08.824+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:48:08.839+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.032 seconds
[2025-04-03T12:48:39.237+0000] {processor.py:154} INFO - Started process (PID=1963) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:48:39.239+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:48:39.240+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:48:39.240+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:48:39.250+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:48:39.267+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.036 seconds
[2025-04-03T12:49:09.358+0000] {processor.py:154} INFO - Started process (PID=2001) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:49:09.361+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:49:09.362+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:49:09.361+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:49:09.368+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:49:09.386+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.033 seconds
[2025-04-03T12:49:39.421+0000] {processor.py:154} INFO - Started process (PID=2036) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:49:39.424+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:49:39.424+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:49:39.424+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:49:39.437+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:49:39.454+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.037 seconds
[2025-04-03T12:50:10.381+0000] {processor.py:154} INFO - Started process (PID=2074) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:50:10.382+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:50:10.383+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:50:10.383+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:50:10.391+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:50:10.404+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.027 seconds
[2025-04-03T12:50:40.617+0000] {processor.py:154} INFO - Started process (PID=2103) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:50:40.617+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:50:40.618+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:50:40.618+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:50:40.621+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:50:40.630+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.015 seconds
[2025-04-03T12:51:11.154+0000] {processor.py:154} INFO - Started process (PID=2137) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:51:11.156+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:51:11.157+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:51:11.157+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:51:11.163+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:51:11.176+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.026 seconds
[2025-04-03T12:51:41.300+0000] {processor.py:154} INFO - Started process (PID=2181) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:51:41.302+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:51:41.302+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:51:41.302+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:51:41.313+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:51:41.335+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.040 seconds
[2025-04-03T12:52:11.854+0000] {processor.py:154} INFO - Started process (PID=2216) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:52:11.855+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:52:11.855+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:52:11.855+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:52:11.860+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:52:11.873+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.023 seconds
[2025-04-03T12:52:42.350+0000] {processor.py:154} INFO - Started process (PID=2254) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:52:42.352+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:52:42.353+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:52:42.353+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:52:42.357+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:52:42.368+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.021 seconds
[2025-04-03T12:53:12.427+0000] {processor.py:154} INFO - Started process (PID=2294) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:53:12.428+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2025-04-03T12:53:12.428+0000] {logging_mixin.py:120} INFO - [2025-04-03T12:53:12.428+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:53:12.431+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2025-04-03T12:53:12.439+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.014 seconds
