[2025-04-28T10:35:41.255+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2025-04-27T00:00:00+00:00 [queued]>
[2025-04-28T10:35:41.359+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2025-04-27T00:00:00+00:00 [queued]>
[2025-04-28T10:35:41.373+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2025-04-28T10:35:41.383+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2025-04-28T10:35:41.390+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2025-04-28T10:35:41.474+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2025-04-27 00:00:00+00:00
[2025-04-28T10:35:41.539+0000] {standard_task_runner.py:55} INFO - Started process 174 to run task
[2025-04-28T10:35:41.609+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2025-04-27T00:00:00+00:00', '--job-id', '253', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpbzo6mg6d']
[2025-04-28T10:35:41.654+0000] {standard_task_runner.py:83} INFO - Job 253: Subtask is_api_available
[2025-04-28T10:35:42.077+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2025-04-27T00:00:00+00:00 [running]> on host fae2b1eff5d6
[2025-04-28T10:35:42.776+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2025-04-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-04-27T00:00:00+00:00
[2025-04-28T10:35:42.810+0000] {http.py:120} INFO - Poking: api/
[2025-04-28T10:35:42.957+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2025-04-28T10:35:43.015+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2025-04-28T10:36:34.026+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2025-04-28T10:36:34.259+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20250427T000000, start_date=20250428T103541, end_date=20250428T103634
[2025-04-28T10:36:34.584+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2025-04-28T10:36:34.994+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
