[2025-04-30T00:18:12.298+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2025-04-29T00:00:00+00:00 [queued]>
[2025-04-30T00:18:12.449+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2025-04-29T00:00:00+00:00 [queued]>
[2025-04-30T00:18:12.459+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2025-04-30T00:18:12.466+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2025-04-30T00:18:12.467+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2025-04-30T00:18:12.626+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2025-04-29 00:00:00+00:00
[2025-04-30T00:18:12.665+0000] {standard_task_runner.py:55} INFO - Started process 12919 to run task
[2025-04-30T00:18:12.740+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2025-04-29T00:00:00+00:00', '--job-id', '310', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpm3p1iog_']
[2025-04-30T00:18:12.804+0000] {standard_task_runner.py:83} INFO - Job 310: Subtask is_api_available
[2025-04-30T03:30:27.689+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2025-04-29T00:00:00+00:00 [running]> on host fae2b1eff5d6
[2025-04-30T03:30:29.268+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2025-04-29T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-04-29T00:00:00+00:00
[2025-04-30T03:30:29.307+0000] {http.py:120} INFO - Poking: api/
[2025-04-30T03:30:29.421+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2025-04-30T03:30:29.477+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2025-04-30T03:30:30.452+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2025-04-30T03:30:30.693+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20250429T000000, start_date=20250430T001812, end_date=20250430T033030
[2025-04-30T03:30:31.102+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2025-04-30T03:30:31.795+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
